package estructuras;

public class Enumerativos {
	
	public enum Movimiento {
		DERECHA, IZQUIERDA, ARRIBA, ABAJO
	}

	public enum TipoBloque {
		LIBRE, BLOQUE, GATO, GATOHORIZONTAL, GATOVERTICAL, GATOESQUINAABAJODERECHA, GATOESQUINAABAJOIZQUIERDA,
		GATOESQUINAARRIBADERECHA, GATOESQUINAARRIBAIZQUIERDA
	}
}
